service: botline

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    BOT_TOKEN: ${env:BOT_TOKEN}
    CHAT_ID: ${env:CHAT_ID}
    REQUEST_TOKEN: ${env:REQUEST_TOKEN}

functions:
  notify:
    handler: dist/handler.handler
    events:
      - httpApi:
          path: /notify
          method: post

package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
    - "!*.md"
    - "!.git/**"
